### ISSUE TITLE
Merging multiple feature arrays

### ISSUE THREAD

**Issue by casper2002casper** [CarloLucibello/GraphNeuralNetworks.jl#102]
I'm a bit confused about using multiple node feature arrays per graph. Using multiple node feature arrays allows keeping apart different features of the node (i.e. x and y values) however when trying to pass it through a layer it outputs an error. Is the intended use to keep all features in a single array? Couldn't all features arrays be merged?

This works
```julia
julia> l = GCNConv(2=>1)
julia> g = rand_graph(4, 6, ndata=(x = ones(2,4)))
julia> l(g)`
GNNGraph:
    num_nodes = 4
    num_edges = 6
    ndata:
        x => (1, 4)
```
This doesn't
```julia
julia> g = rand_graph(4, 6, ndata=(x = ones(4), y = zeros(4)))  
julia> l(g)  
┌ Error: Multiple feature arrays, access directly through g.ndata
└ @ GraphNeuralNetworks.GNNGraphs ~/.julia/packages/GraphNeuralNetworks/KNr8R/src/GNNGraphs/query.jl:321
ERROR: MethodError: no method matching (::GCNConv{Matrix{Float32}, Vector{Float32}, typeof(identity)})(::GNNGraph{Tuple{Vector{Int64}, Vector{Int64}, Nothing}}, ::Nothing)
```

**Comment by CarloLucibello** [comment]
Yes, typically one keeps all features in a single array (e.g. one matrix of size `num_features x num_nodes`). 
We allow the possibility to store separate feature arrays since in some applications they are handled in a different way (see equivariant graph neural networks for instance). 

PS using [julia code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) will make your code mode readable

**Comment by casper2002casper** [comment]
I see, thank you
